# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 02:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_integration_app', '0002_auto_20160919_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='type',
            field=models.CharField(choices=[('products', 'products'), ('tlog', 'tlog'), ('flyer', 'flyer'), ('pricing', 'pricing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='integration_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('sku_upc_prd_map', 'sku_upc_prd_map'), ('stores', 'stores'), ('tax', 'tax'), ('categories', 'categories'), ('store_products', 'store_products'), ('product_locations', 'product_locations'), ('product_images', 'product_images'), ('product_details', 'product_details'), ('product_nutritions', 'product_nutritions'), ('tlog_headers', 'tlog_headers'), ('tlog_lineitems', 'tlog_lineitems'), ('flyer_delete', 'flyer_delete'), ('flyer', 'flyer'), ('base_price_delete', 'base_price_delete'), ('base_price_delta', 'base_price_delta'), ('base_price_full', 'base_price_full'), ('sale_price_delete', 'sale_price_delete'), ('sale_price_delta', 'sale_price_delta'), ('sale_price_full', 'sale_price_full')], max_length=100),
        ),
    ]
